### ISSUE TITLE
no hdmi after upgrade to 6.9.5

### ISSUE THREAD

**Issue by leelists** [inindev/linux-rockchip#1]
Hi,

A few days ago, I started using this repo to get a recent mainline kernel for my nanopc-t6.
I did that with the 6.9.4 kernel version an all is good for me.

But since I tried the 6.9.5 kernel and lost HDMI output. Reverting to 6.9.4 fixes the issue.

How can i help ?

**Comment by inindev** [comment]
Thank you for the feedback.  I updated to the linux config Debian uses and I must have dropped a kernel module.
https://github.com/inindev/linux-rockchip/commit/cd1f27d49fc64eabaac7ae8c50550b6e94802655#diff-c175f5a644886216903695409cfd69d68ecc091a1e60a9b9f018e7413bd738ef

This should be easy to fix.

**Comment by inindev** [comment]
I have published a 6.9.5 kernel with working video: https://github.com/inindev/linux-rockchip/releases/tag/v6.9.5-2

**Comment by leelists** [comment]
I confirm, it's working again, great job
