### ISSUE TITLE
RK3588 and Rock 5B dts additions: thermal, OPP and fan

### ISSUE THREAD

**Issue by leelists** [inindev/linux-rockchip#2]
The https://lkml.org/lkml/2024/6/17/1445 patch seems to be an interesting addition to this project, what do you think?

**Comment by inindev** [comment]
The v3 version of this patch is already in there:
https://github.com/inindev/linux-rockchip/blob/main/patches/02_collabora/0005-arm64-dts-rockchip-enable-built-in-thermal-monitorin.patch
https://github.com/inindev/linux-rockchip/blob/main/patches/02_collabora/0006-arm64-dts-rockchip-enable-automatic-active-cooling-o.patch
https://github.com/inindev/linux-rockchip/blob/main/patches/02_collabora/0007-arm64-dts-rockchip-Add-CPU-memory-regulator-coupling.patch
https://github.com/inindev/linux-rockchip/blob/main/patches/02_collabora/0008-arm64-dts-rockchip-Add-OPP-data-for-CPU-cores-on-RK3.patch
https://github.com/inindev/linux-rockchip/blob/main/patches/02_collabora/0009-arm64-dts-rockchip-Add-further-granularity-in-RK3588.patch

I will be sure to update to v5 when I build 6.9.6 in a couple of days:
https://lore.kernel.org/linux-patches/35d6ea79-3b6c-4304-b3bc-2d7c9b77b277@gmail.com

**Comment by inindev** [comment]
This version contains the lates thermal patches:
https://github.com/inindev/linux-rockchip/releases/tag/v6.9.6

**Comment by leelists** [comment]
Thank you very much :+1:
