### ISSUE TITLE
Missing rockchip.mpp-service tree node

### ISSUE THREAD

**Issue by thomasbergersen** [inindev/linux-rockchip#3]
Missing rockchip.mpp-service node in the device tree. If this node can be added, desktop video encoding and decoding will work. Thanks in advance.

![IMG_9281](https://github.com/user-attachments/assets/f9b02680-a638-410b-a8c7-c026bb034530)

![IMG_9280](https://github.com/user-attachments/assets/f27df479-413e-401e-92f9-e4bce964d149)

**Comment by inindev** [comment]
Hi Thomas, thanks for the report. From searching around, mpp-srv looks to be a vendor-specific implementation in their down-stream repo.

This project tracks the upstream patches being merged into the Linux tree. Collabora has a very nice wiki where they are tracking upstream support for rk3588 devices:
https://gitlab.collabora.com/hardware-enablement/rockchip-3588/notes-for-rockchip-3588/-/blob/main/mainline-status.md
